spring:
  profiles.active: dev
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      javax.persistence.validation.mode: AUTO
      eclipselink:
        jdbc.allow-native-sql-queries: true
        ddl-generation: none
        cache.shared.default: false
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      initial-size: 3
      max-wait: 3000
      db-properties:
        currentSchema: unitymessage
        stringtype: unspecified
  kafka:
    bootstrapAddress: localhost:9092
    topicName: unityMessageQueue
    producer:
      transaction-id-prefix: tx
      enable.idempotence: true
  output:
    ansi:
      enabled: ALWAYS
  web.resources.add-mappings: false
server.port: 8090
logbook.format.style: http
---
spring:
  config.activate.on-profile: cloud
  datasource:
    url: ${credentials.jdbc_uri}
    username: ${credentials.username}
    password: ${credentials.password}
    tomcat:
      db-properties:
        ssl: true
        sslmode: verify-full

log.http.level: ERROR
log.app.level: WARN